import React, { createContext, useState, useEffect, useContext } from 'react';

const translations = {
  en: {
    home: 'Home',
    about: 'About',
    services: 'Programs',
    testimonials: 'Success story',
    gallery: 'Gallery',
    features: 'Why Us',
    blog: 'Blog',
    getHelp: 'Get Help Now',
    startRecovery: 'Start Your Recovery',
    heroLine1: 'Break Free from',
    heroLine2: 'Healthier Addiction Free',
    taglinePart1: 'Professional, Compassionate & Effective',
    taglinePart2: 'Alcohol De-addiction Treatment',
    heroDescription: ' Yugantar provides Services Offered with expert medical guidance. Start your journey toward a healthier, alcohol-free life today with compassionate care that transforms lives.',
    contactHeading: 'Get Help Today',
    aboutHeading: 'Your Transformation begins here',
    aboutParagraph1: 'Take full charge of your life and confidently step into a healthier, happier future. We are always here to support you with practical guidance, effective tools, and a compassionate community that truly understands your journey. Our programs help individuals overcome alcohol addiction through structured treatment, emotional support, and evidence-based recovery strategies.',
    aboutParagraph2: 'With proven methods, expert medical guidance, and inspiring real-life recovery stories, we help individuals break free from alcohol addiction and reclaim control over their lives. Our structured rehabilitation programs focus on physical healing, mental strength, and emotional balance, making recovery not only achievable but truly empowering and life-changing. Every step you take with us moves you closer to an alcohol-free life filled with renewed energy, confidence, self-respect, freedom, and lasting inner happiness.',
    featuresHeading: 'Why Choose Yugantar',
    featuresSub: 'Compassionate, professional and nature-driven rehabilitation care',
    galleryHeading: 'Photo Gallery',
    servicesHeading: 'Our Programs',
    testimonialsHeading: 'Success Stories',
    expertsHeading: 'Meet Our Expert Team',
    ctaTitle: 'Begin Your Path to Recovery',
    ctaPhone: 'Call Now',
    contactFormName: 'Full Name *',
    contactFormPhone: 'Phone Number *',
    contactFormEmail: 'Email Address',
    contactFormProgram: 'Program Interested In *',
    messagePlaceholder: 'Your Message',
    submitButton: 'Submit',
    directEnquiry: 'Send Your Direct Enquiry',
    consultationHeading: 'Free Confidential Consultation',
    consultationDesc: 'Fill the form below and our expert will contact you shortly',
    helplineLabel: '24/7 Helpline',
    helplineDetails: '+91 12345 67890',
    helplineDesc: 'Call anytime for immediate assistance',
    emailLabel: 'Email',
    emailDetails: 'help@yugantar.com',
    emailDesc: 'Response within 2 hours',
    locationLabel: 'Location',
    locationDetails: 'Pataleshwar Complex , SDO road , Hajipur - 800',
    hoursLabel: 'Working Hours',
    hoursDetails: 'Mon - Sun, 9:00 AM - 8:00 PM',
    hoursDesc: 'Emergency: 24/7',
    firstStepDesc: 'Take the First Step Towards Recovery – Confidential & Professional Help Available 24/7',
    firstStepBadge: 'Take the First Step Today',
    expertTeamDesc: 'Our experienced team of addiction specialists is available around the clock to provide confidential support and guidance tailored to your unique situation.',
    freeConsultation: 'Free Consultation',
    noCommitment: 'No commitment required',
    confidential: '100% Confidential',
    privacyGuaranteed: 'Privacy guaranteed',
    available24: '24/7 Availability',
    helpWhenNeeded: 'Help when you need it',
    thankyouHeading: 'Thank You!',
    thankYouMessage: 'We have received your request. Our expert will contact you shortly.',
    service1: '12 Step Program',
    service2: 'Alcoholism Treatment',
    service3: 'Ayurveda Treatment',
    service4: 'Counseling',
    service5: 'AA & NA Meetings',
    service6: 'Anxiety Management',
    service7: 'Corporate Program',
    service8: 'Depression Treatment',
    viewMore: 'View More',
    feature1: 'All Kinds Of Services For Addiction & Mental Health',
    feature1Desc: 'A range of treatment services for any & every kind of addiction & mental health problem.',
    feature2: 'Scientifically Guided Alcohol Rehabilitation',
    feature2Desc: ' Through scientifically guided alcohol de-addiction treatment, we ensure safe, effective, and long-lasting recovery.',
    feature3: 'Government Authorized',
    feature3Desc: 'A government authorised facility that you can trust with your loved ones and rely upon.',
    feature4: 'Customised & Client-Based Treatment Options',
    feature4Desc: 'Personalised treatment strategies to carve every individual\'s unique path to recovery.',
    feature5: 'Team Of Experts',
    feature5Desc: 'A team of trained & highly experienced individuals to address the unique challenges of every patient.',
    feature6: 'Holistic Treatment Approach',
    feature6Desc: 'A holistic modern treatment approach to help patients recover physically, mentally, & emotionally.',
    expertsSubtitle: 'Experienced professionals dedicated to ethical, compassionate, and long-term recovery',
    expert1Name: 'Mrs. Gayathri Arvind',
    expert1Role: 'Founder & Managing Director',
    expert1Desc: 'Mrs. Gayathri Arvind is an entrepreneur, philanthropist, and mental health advocate. She founded Abhasa with the vision of providing a humane, holistic, and compassionate approach to addiction recovery. Her focus is on physical, mental, and emotional healing without coercion or suppression, ensuring dignity and long-term wellness for every individual.',
    expert2Name: 'Dr. Rohit Garg',
    expert2Role: 'Senior Consultant & Managing Director',
    expert2Desc: 'Dr. Rohit Garg is the Director of Mind Vriksha Clinic, New Delhi, and plays a pivotal role in addiction treatment at Abhasa. He specializes in adult, child, and geriatric psychiatry, providing expert care across all age groups. Dr. Garg is renowned for his work in Cognitive Behavioral Therapy and advanced neuropsychiatric techniques, combining science with empathy to achieve effective outcomes.',
    expert3Name: 'Dr. Ananya Sharma',
    expert3Role: 'Consultant Psychiatrist',
    expert3Desc: 'Dr. Ananya Sharma is a consultant psychiatrist with extensive experience in addiction psychiatry, mood disorders, and trauma-focused care. She emphasizes evidence-based treatment combined with empathy, ensuring each patient receives personalized care. Her approach focuses on dignity, understanding, and long-term mental wellness for every individual.',
    footerBrandAbout: 'Helping individuals overcome alcohol addiction through evidence-based programs, compassionate care, and professional support since 2008.',
    footerHeadOffice: 'Head Office:',
    footerHelpline: 'Helpline:',
    footerEmail: 'Email:',
    footerEmergency: 'Emergency:',
    footerQuickLinks: 'Quick Links',
    footerHome: 'Home',
    footerAboutUs: 'About Us',
    footerPrograms: 'Our Programs',
    footerWhyChoose: 'Why Choose Us',
    footerSuccess: 'Success Stories',
    footerContactUs: 'Contact Us',
    footerOurPrograms: 'Our Programs',
    footerDetox: 'Detoxification',
    footerResidential: 'Residential Rehab',
    footerOutpatient: 'Outpatient Program',
    footerAftercare: 'Aftercare Support',
    footerFamilyCounseling: 'Family Counseling',
    footerRelapsePrevention: 'Relapse Prevention',
    footerResources: 'Resources',
    footerBlog: 'Blog & Articles',
    footerFAQs: 'FAQs',
    footerTreatment: 'Treatment Process',
    footerSuccessRates: 'Success Rates',
    footerInsurance: 'Insurance Info',
    footerCareers: 'Career Opportunities',
    footerCopyright: 'Yugantar Alcohol De-addiction Center. All rights reserved.',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerDisclaimer: 'Disclaimer',
    footerSitemap: 'Sitemap',
    testimonialsSubtitle: 'Real people, real transformations',
    noObligation: 'No obligation required',
    confidentialInfo: 'All information kept strictly confidential',
    insuranceHelp: 'Insurance verification assistance available',
    whyContactYugantar: 'Why Contact Yugantar?',
    consultation1: 'Free initial consultation and assessment',
    consultation2: 'No obligation, completely confidential',
    consultation3: 'Insurance and payment plan assistance',
    consultation4: 'Immediate admission available',
    consultation5: 'Family support and counseling',
    expertMedical: 'Expert Medical Team',
    completePrivacy: 'Complete Privacy',
    evidenceBased: 'Evidence-Based Care',
    roundClock: 'Round-the-Clock Support',
    successRate: '95% Success Rate • Verified Treatment',
    livesTransformed: '1000+ Lives Transformed',
    testimonial1Name: 'Rahul Mehta',
    testimonial1Duration: 'Alcohol-free for 3 years',
    testimonial1Quote: 'Yugantar saved my life. After 15 years of alcohol dependency, I had lost all hope. The compassionate staff and structured program helped me rebuild my life from scratch. Today, I\'m running my business successfully and enjoying time with my family.',
    testimonial2Name: 'Sanjay Kumar',
    testimonial2Duration: 'Sober for 2 years',
    testimonial2Quote: 'The holistic approach at Yugantar made all the difference. It wasn\'t just about quitting alcohol, but learning to live without it. The aftercare support has been invaluable in maintaining my sobriety through challenging times.',
    testimonial3Name: 'Vikram Singh',
    testimonial3Duration: 'Alcohol-free for 4 years',
    testimonial3Quote: 'As a businessman, I was skeptical about rehabilitation. But Yugantar\'s professional approach and complete privacy convinced me. The medical team was exceptional, and the counseling sessions changed my perspective on life.',
    testimonial4Name: 'Anita Desai',
    testimonial4Relation: 'Wife of a patient',
    testimonial4Quote: 'My husband\'s transformation at Yugantar has been miraculous. The family counseling sessions helped us heal our relationship and communicate better. We\'re grateful to the entire team for giving us our family back.',
    testimonial5Name: 'Rohit Nair',
    testimonial5Duration: 'Sober for 18 months',
    testimonial5Quote: 'The medical supervision during detox was excellent. The staff was always available, and the therapy sessions helped me understand my triggers. The aftercare program keeps me accountable and supported.',
    languageToggle: 'हिंदी',
  },
  hi: {
    home: 'होम',
    about: 'हमारे बारे में',
    services: 'प्रोग्राम',
    testimonials: 'सफलता की कहानियाँ',
    gallery: 'गैलरी',
    features: 'क्यों चुनें',
    blog: 'ब्लॉग',
    getHelp: 'अब मदद लें',
    startRecovery: 'अपनी रिकवरी शुरू करें',
    heroLine1: 'मुक्त हो जाएँ',
    heroLine2: 'शराब की लत से',
    taglinePart1: 'पेशेवर, सहानुभूतिपूर्ण और प्रभावी',
    taglinePart2: 'शराब मुक्ति उपचार',
    heroDescription: ' युगांतर विशेषज्ञ चिकित्सकीय मार्गदर्शन के साथ सेवाएँ प्रदान करता है।करुणामय देखभाल के साथ आज ही एक स्वस्थ, शराब-मुक्त जीवन की ओर अपनी यात्रा शुरू करें, जो जीवन में सकारात्मक परिवर्तन लाती है।',
    contactHeading: 'आज ही मदद लें',
    aboutHeading: 'आपका परिवर्तन यहीं से शुरू होता है',
    aboutParagraph1: 'अपनी ज़िंदगी का पूरा नियंत्रण लें और स्वस्थ, खुशहाल भविष्य की ओर आत्मविश्वास के साथ कदम बढ़ाएँ। हम व्यावहारिक मार्गदर्शन, प्रभावी उपकरण और सहानुभूतिपूर्ण समुदाय के साथ सदैव आपका समर्थन करते हैं। हमारे कार्यक्रम संरचित उपचार, भावनात्मक सहायता और साक्ष्य-आधारित रिकवरी रणनीतियों के जरिए व्यक्तियों को शराब की लत से लड़ने में मदद करते हैं।',
    aboutParagraph2: ' सिद्ध तरीकों, विशेषज्ञ चिकित्सकीय मार्गदर्शन और प्रेरणादायक वास्तविक जीवन की रिकवरी कहानियों के माध्यम से हम लोगों को शराब की लत से मुक्त होने और अपने जीवन पर फिर से नियंत्रण पाने में मदद करते हैं। हमारे संरचित पुनर्वास कार्यक्रम शारीरिक स्वास्थ्य, मानसिक मजबूती और भावनात्मक संतुलन पर केंद्रित हैं, जिससे रिकवरी न केवल संभव होती है बल्कि वास्तव में सशक्त और जीवन-परिवर्तनकारी बनती है। हमारे साथ उठाया गया हर कदम आपको शराब-मुक्त जीवन के और करीब ले जाता है—जो नई ऊर्जा, आत्मविश्वास, आत्मसम्मान, स्वतंत्रता और स्थायी आंतरिक सुख से भरपूर होता है।',
    featuresHeading: 'क्यों चुनें युगांतर',
    featuresSub: 'दयालु, पेशेवर और प्रकृति-संचालित पुनर्वास देखभाल',
    galleryHeading: 'फोटो गैलरी',
    servicesHeading: 'हमारे कार्यक्रम',
    testimonialsHeading: 'सफलता की कहानियाँ',
    expertsHeading: 'हमारी विशेषज्ञ टीम से मिलें',
    ctaTitle: 'अपनी रिकवरी की शुरुआत करें',
    ctaPhone: 'अब कॉल करें',
    contactFormName: 'पूरा नाम *',
    contactFormPhone: 'फोन नंबर *',
    contactFormEmail: 'ईमेल पता',
    contactFormProgram: 'रुचिकर प्रोग्राम *',
    messagePlaceholder: 'आपका संदेश',
    submitButton: 'सबमिट करें',
    directEnquiry: 'अपना सीधा पूछताछ भेजें',
    consultationHeading: 'मुफ्त गोपनीय परामर्श',
    consultationDesc: 'नीचे दिए गए फॉर्म को भरें और हमारा विशेषज्ञ जल्द ही आपसे संपर्क करेगा',
    helplineLabel: '24/7 हेल्पलाइन',
    helplineDetails: '+91 12345 67890',
    helplineDesc: 'तुरंत सहायता के लिए कभी भी कॉल करें',
    emailLabel: 'ईमेल',
    emailDetails: 'help@yugantar.com',
    emailDesc: '2 घंटे के अंदर जवाब मिलेगा',
    locationLabel: 'स्थान',
    locationDetails: 'पतालेश्वर परिसर , SDO सड़क , हाजीपुर - 800',
    hoursLabel: 'काम के घंटे',
    hoursDetails: 'सोम - रविवार, 9:00 AM - 8:00 PM',
    hoursDesc: 'आपातकाल: 24/7',
    firstStepDesc: 'रिकवरी की ओर पहला कदम बढ़ाएँ – गोपनीय और व्यावसायिक सहायता 24/7 उपलब्ध',
    firstStepBadge: 'आज ही पहला कदम बढ़ाएँ',
    expertTeamDesc: 'हमारी अनुभवी लत विशेषज्ञों की टीम आपकी अद्वितीय परिस्थिति के लिए तैयार गोपनीय समर्थन और मार्गदर्शन प्रदान करने के लिए सदा तैयार है।',
    freeConsultation: 'मुफ्त परामर्श',
    noCommitment: 'कोई दायित्व नहीं',
    confidential: '100% गोपनीय',
    privacyGuaranteed: 'गोपनीयता की गारंटी',
    available24: '24/7 उपलब्ध',
    helpWhenNeeded: 'जरूरत के समय मदद',
    thankyouHeading: 'धन्यवाद!',
    thankYouMessage: 'हमने आपकी अनुरोध प्राप्त कर ली है। हमारा विशेषज्ञ जल्द ही आपसे संपर्क करेगा।',
    service1: '12 स्टेप प्रोग्राम',
    service2: 'शराब की लत का इलाज',
    service3: 'आयुर्वेद उपचार',
    service4: 'परामर्श',
    service5: 'AA और NA मीटिंग',
    service6: 'चिंता प्रबंधन',
    service7: 'कॉर्पोरेट प्रोग्राम',
    service8: 'डिप्रेशन उपचार',
    viewMore: 'और देखें',
    feature1: 'लत और मानसिक स्वास्थ्य के लिए सभी प्रकार की सेवाएँ',
    feature1Desc: 'किसी भी तरह की लत और मानसिक स्वास्थ्य समस्या के लिए उपचार सेवाओं की एक विस्तृत श्रृंखला।',
    feature2: 'वैज्ञानिक मार्गदर्शन के साथ शराब नशा मुक्ति',
    feature2Desc: 'वैज्ञानिक पद्धति से संचालित शराब नशा मुक्ति उपचार के माध्यम से हम सुरक्षित, प्रभावी और स्थायी रिकवरी सुनिश्चित करते हैं।',
    feature3: 'सरकार द्वारा अधिकृत',
    feature3Desc: 'एक सरकार द्वारा अधिकृत सुविधा जिस पर आप अपने प्रियजनों के साथ भरोसा कर सकते हैं।',
    feature4: 'अनुकूलित और ग्राहक-आधारित उपचार विकल्प',
    feature4Desc: 'व्यक्तिगत उपचार रणनीतियाँ जो हर व्यक्ति के रिकवरी के अद्वितीय मार्ग को तैयार करती हैं।',
    feature5: 'विशेषज्ञों की टीम',
    feature5Desc: 'प्रशिक्षित और अत्यधिक अनुभवी व्यक्तियों की एक टीम जो हर रोगी की अद्वितीय चुनौतियों का समाधान करती है।',
    feature6: 'समग्र उपचार दृष्टिकोण',
    feature6Desc: 'एक समग्र आधुनिक उपचार दृष्टिकोण जो रोगियों को शारीरिक, मानसिक और भावनात्मक रूप से ठीक होने में मदद करता है।',
    expertsSubtitle: 'नैतिक, दयालु और दीर्घकालीन रिकवरी के लिए समर्पित अनुभवी पेशेवर',
    expert1Name: 'श्रीमती गायत्री अरविंद',
    expert1Role: 'संस्थापक और प्रबंध निदेशक',
    expert1Desc: 'श्रीमती गायत्री अरविंद एक उद्यमी, परोपकारी और मानसिक स्वास्थ्य वकील हैं। उन्होंने अभास की स्थापना की दृष्टि के साथ की कि लत की रिकवरी के लिए एक मानवीय, समग्र और दयालु दृष्टिकोण प्रदान किया जाए। उनका ध्यान शारीरिक, मानसिक और भावनात्मक उपचार पर है बिना जबरदस्ती या दमन के, हर व्यक्ति के लिए सम्मान और दीर्घकालीन कल्याण सुनिश्चित करते हुए।',
    expert2Name: 'डॉ. रोहित गर्ग',
    expert2Role: 'वरिष्ठ सलाहकार और प्रबंध निदेशक',
    expert2Desc: 'डॉ. रोहित गर्ग दिल्ली के माइंड वृक्ष क्लिनिक के निदेशक हैं और अभास में लत उपचार में महत्वपूर्ण भूमिका निभाते हैं। वे वयस्क, बाल और बुजुर्ग मनोरोग में विशेषज्ञता रखते हैं, सभी आयु समूहों को विशेषज्ञ देखभाल प्रदान करते हैं। डॉ. गर्ग संज्ञानात्मक व्यवहार चिकित्सा और उन्नत न्यूरोसाइकिएट्रिक तकनीकों में अपने काम के लिए प्रसिद्ध हैं, विज्ञान को सहानुभूति के साथ जोड़कर प्रभावी परिणाम प्राप्त करते हैं।',
    expert3Name: 'डॉ. अनन्या शर्मा',
    expert3Role: 'सलाहकार मनोरोग विशेषज्ञ',
    expert3Desc: 'डॉ. अनन्या शर्मा एक सलाहकार मनोरोग विशेषज्ञ हैं जिन्हें लत मनोरोग, मानसिक विकार और आघात केंद्रित देखभाल में व्यापक अनुभव है। वह सहानुभूति के साथ सबूत-आधारित उपचार पर जोर देती हैं, यह सुनिश्चित करते हुए कि प्रत्येक रोगी को व्यक्तिगत देखभाल मिले। उनका दृष्टिकोण हर व्यक्ति के लिए सम्मान, समझ और दीर्घकालीन मानसिक कल्याण पर केंद्रित है।',
    footerBrandAbout: 'व्यक्तियों को 2008 से साक्ष्य-आधारित कार्यक्रमों, दयालु देखभाल और व्यावसायिक समर्थन के माध्यम से शराब की लत से उबरने में मदद करना।',
    footerHeadOffice: 'मुख्य कार्यालय:',
    footerHelpline: 'हेल्पलाइन:',
    footerEmail: 'ईमेल:',
    footerEmergency: 'आपातकाल:',
    footerQuickLinks: 'त्वरित लिंक',
    footerHome: 'होम',
    footerAboutUs: 'हमारे बारे में',
    footerPrograms: 'हमारे कार्यक्रम',
    footerWhyChoose: 'क्यों चुनें',
    footerSuccess: 'सफलता की कहानियाँ',
    footerContactUs: 'संपर्क करें',
    footerOurPrograms: 'हमारे कार्यक्रम',
    footerDetox: 'विषमुक्तिकरण',
    footerResidential: 'आवासीय पुनर्वास',
    footerOutpatient: 'बाहरी रोगी कार्यक्रम',
    footerAftercare: 'उपचार के बाद सहायता',
    footerFamilyCounseling: 'पारिवारिक परामर्श',
    footerRelapsePrevention: 'पुनरावृत्ति रोकथाम',
    footerResources: 'संसाधन',
    footerBlog: 'ब्लॉग और लेख',
    footerFAQs: 'सामान्य प्रश्न',
    footerTreatment: 'उपचार प्रक्रिया',
    footerSuccessRates: 'सफलता दर',
    footerInsurance: 'बीमा जानकारी',
    footerCareers: 'करियर के अवसर',
    footerCopyright: 'युगांतर अल्कोहल डि-एडिक्शन सेंटर। सर्वाधिकार सुरक्षित।',
    footerPrivacy: 'गोपनीयता नीति',
    footerTerms: 'सेवा की शर्तें',
    footerDisclaimer: 'अस्वीकरण',
    footerSitemap: 'साइटमैप',
    testimonialsSubtitle: 'असली लोग, असली बदलाव',
    noObligation: 'कोई दायित्व नहीं',
    confidentialInfo: 'सभी जानकारी पूरी तरह गोपनीय रखी जाती है',
    insuranceHelp: 'बीमा सत्यापन सहायता उपलब्ध है',
    whyContactYugantar: 'युगांतर से संपर्क क्यों करें?',
    consultation1: 'मुफ्त प्रारंभिक परामर्श और मूल्यांकन',
    consultation2: 'कोई दायित्व नहीं, पूरी तरह गोपनीय',
    consultation3: 'बीमा और भुगतान योजना सहायता',
    consultation4: 'तत्काल प्रवेश उपलब्ध',
    consultation5: 'पारिवारिक समर्थन और परामर्श',
    expertMedical: 'विशेषज्ञ चिकित्सा टीम',
    completePrivacy: 'पूर्ण गोपनीयता',
    evidenceBased: 'साक्ष्य-आधारित देखभाल',
    roundClock: 'चौबीस घंटे समर्थन',
    successRate: '95% सफलता दर • सत्यापित उपचार',
    livesTransformed: '1000+ जीवन बदले गए',
    testimonial1Name: 'राहुल मेहता',
    testimonial1Duration: '3 साल से शराब मुक्त',
    testimonial1Quote: 'युगांतर ने मेरी जान बचाई। 15 साल की शराब की लत के बाद, मैंने सभी आशा खो दी थी। दयालु कर्मचारियों और संरचित कार्यक्रम ने मुझे शुरुआत से ही अपना जीवन फिर से बनाने में मदद की। आज, मैं अपना व्यवसाय सफलतापूर्वक चला रहा हूँ और अपने परिवार के साथ समय बिता रहा हूँ।',
    testimonial2Name: 'संजय कुमार',
    testimonial2Duration: '2 साल से सोबर',
    testimonial2Quote: 'युगांतर का समग्र दृष्टिकोण सभी अंतर ला गया। यह केवल शराब छोड़ने के बारे में नहीं था, बल्कि इसके बिना रहना सीखने के बारे में था। उपचार के बाद की सहायता चुनौतीपूर्ण समय में मेरी संतुष्टि बनाए रखने में अमूल्य साबित हुई है।',
    testimonial3Name: 'विक्रम सिंह',
    testimonial3Duration: '4 साल से शराब मुक्त',
    testimonial3Quote: 'एक व्यवसायी के रूप में, मैं पुनर्वास के बारे में संदेहजनक था। लेकिन युगांतर के व्यावसायिक दृष्टिकोण और पूर्ण गोपनीयता ने मुझे आश्वस्त किया। चिकित्सा टीम असाधारण थी, और परामर्श सत्रों ने मेरे जीवन के प्रति मेरे दृष्टिकोण को बदल दिया।',
    testimonial4Name: 'अनिता देसाई',
    testimonial4Relation: 'रोगी की पत्नी',
    testimonial4Quote: 'मेरे पति का युगांतर में रूपांतरण चमत्कारी रहा है। पारिवारिक परामर्श सत्रों ने हमें अपने संबंध को ठीक करने और बेहतर संचार करने में मदद की। हम पूरी टीम के लिए आभारी हैं कि उन्होंने हमें हमारा परिवार वापस दिया।',
    testimonial5Name: 'रोहित नायर',
    testimonial5Duration: '18 महीने से सोबर',
    testimonial5Quote: 'डिटॉक्स के दौरान चिकित्सा पर्यवेक्षण उत्कृष्ट था। कर्मचारी हमेशा उपलब्ध रहते थे, और थेरेपी सत्रों ने मुझे अपने ट्रिगर को समझने में मदद की। उपचार के बाद का कार्यक्रम मुझे जवाबदेह और समर्थित रखता है।',
    languageToggle: 'EN',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('lang') || 'en';
    } catch (e) { void e; return 'en'; }
  });

  useEffect(() => {
    try {
      localStorage.setItem('lang', lang);
    } catch (e) { void e; }
  }, [lang]);

  const t = (key) => {
    return translations[lang] && translations[lang][key]
      ? translations[lang][key]
      : translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
